governance/aws/restrict-iam-policy-statement.sentinel

Nic Jackson Helped me put this together. This example ensures that a wildcard is not used in the iampassrole statement

adding iam sentinel example

---

governance/aws/enforce-mandatory-tags.sentinel

Shamelessly copied from other work, but creating an easy to use  policy for examples and usage with our N.E.P.T.R.

add-gov-aws-tags: adding in tags enforcement example

---

infrastructure-as-code/k8s-cluster-gke/main.tf

Newer versions of GKE that are used by default were preventing cats-and-dogs service account from being created.  @lanceplarsen figured out that a fix is to add enable_legacy_abac = "true" to the google_container_cluster resource.  This PR includes that.

added enable_legacy_abac=true to fix GCP issue

---

infrastructure-as-code/azure-vm/main.tf

Setting resource group in all modules will avoid conflicts in cases where multiple SEs use this code at the same time.  Previously, resource group was set to "terraform-compute"

set resource group in modules

---

infrastructure-as-code/terraform-gcp-cloudsql/.gitignore
infrastructure-as-code/terraform-gcp-cloudsql/LICENSE
infrastructure-as-code/terraform-gcp-cloudsql/README.md
infrastructure-as-code/terraform-gcp-cloudsql/examples/prod-and-dev/README.md
infrastructure-as-code/terraform-gcp-cloudsql/examples/prod-and-dev/main.tf
infrastructure-as-code/terraform-gcp-cloudsql/examples/simple/README.md
infrastructure-as-code/terraform-gcp-cloudsql/examples/simple/main.tf
infrastructure-as-code/terraform-gcp-cloudsql/main.tf
infrastructure-as-code/terraform-gcp-cloudsql/outputs.tf
infrastructure-as-code/terraform-gcp-cloudsql/variables.tf

Added terraform-gcp-cloudsql/ under infrastructure-as-code/ for provisioning Google Cloud SQL for PostgreSQL instances. Provided example module code as well.

Initial commit for terraform-gcp-cloudsql

---

governance/vmware/restrict-vm-disk-size.sentinel

In my testing of this policy, the disk.size value was being returned as a string. By specifying it to be an int, the policy works.

Hard Set Type for the disk.size value to int

---

governance/aws/enforce-ami-owners.sentinel

This adds `enforce-ami-owners.sentinel`, which can be used to enforce the
owners list in all `aws_ami` data sources in a Terraform workspace.
Features:
* Leverages `tfconfig`, enforcing that the AMI list is actually declared
in configuration, ensuring that values are physically present before any
planning or applies happen.
* Matches declared owners against an expected allow list. Any owner
outside of the allow list results in a failed result.
* Empty owner lists are rejected.
* Resources in violation of the allow list are logged.
* Aggregates results to avoid Sentinel short circuits so that all
violating config instances can be seen at once.
* Displays the full resource address for each violating resource,
properly joined for ease of viewing.
As a consequence of the runtime lacking a …

governance/aws: Add enforce-ami-owners.sentinel for aws_ami data source

---

governance/aws/enforce-tag-from-data-source.sentinel

Sentinel allows the use of Data Sources in policy evaluation. This policy is an example of using an AWS Data Source;  it restricts the creation of EC2 instances based on value of `Env` tag. 
- The allowable value `Env` is obtained from an [aws_subnet Data Source](https://www.terraform.io/docs/providers/aws/d/subnet.html). 
- `Env` tag from EC2 must match `Env` tag of `aws_subnet` for the policy to pass. 
Note: The `aws_subnet` resource may have been provisioned in a separate Terraform Workspace, or even outside out Terraform altogether. Hence, using a Data Source in Sentinel policy evaluation provides more flexibility.

using data source in policy eval example

---

governance/aws/restrict-iam-policy-statement2.sentinel

This is slightly different from the existing checker in that it allows you to define a list of forbidden actions.   Though using IAM objects, this could be extended to any services IAM actions.

sentinel-updates: adding in another IAM policy checker

---

infrastructure-as-code/k8s-cluster-openshift-aws/README.md
infrastructure-as-code/k8s-cluster-openshift-aws/main.tf
infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/01-amis.tf
infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/05-nodes.tf
infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/07-bastion.tf
infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/files/install-from-bastion.sh
infrastructure-as-code/k8s-cluster-openshift-aws/scripts/postinstall-master.sh

Updated k8s-cluster-openshift-aws to use OpenShift 3.11 (from previous 3.7).  This was actually forced upon us because the code for OpenShift 3.7 could no longer successfully deploy the OpenShift router that is needed for the route that exposes the cats-and-dogs application in the self-serve-infrastructure/k8s-services-openshift directory of this repository.
I was not able to figure out why OpenShift 3.7 broke, but upgrading to 3.11 fixed the problem with the Router.  Adding an extra 3 minute sleep in the configure_k8s remote-exec provisioner fixed a second problem with the kubectl commands in that provisioner failing because the OpenShift API server was not yet fully running.

openshift 3.11

---

governance/azure/block-allow-all-cidr.sentinel

It appears 0.0.0.0 is also valid here.  Added it for more coverage.

Catch 0.0.0.0

---

infrastructure-as-code/terraform-0.12-examples/README.md
infrastructure-as-code/terraform-0.12-examples/for-expressions/main.tf
infrastructure-as-code/terraform-0.12-examples/new-template-syntax/actual_vote.txt
infrastructure-as-code/terraform-0.12-examples/new-template-syntax/main.tf
infrastructure-as-code/terraform-0.12-examples/new-template-syntax/rigged_vote.txt

Updated the Terraform 0.12 examples to use some new things in the Terraform 0.12 beta that were not in any of the alphas.  In particular, the full splat operator, lists in conditional expressions, and the new template syntax inside template files.

update 0.12 examples for beta1

---

infrastructure-as-code/k8s-cluster-gke/README.md
infrastructure-as-code/k8s-cluster-gke/main.tf
infrastructure-as-code/k8s-cluster-gke/outputs.tf
infrastructure-as-code/k8s-cluster-gke/variables.tf
infrastructure-as-code/k8s-vault-config/README.md
infrastructure-as-code/k8s-vault-config/main.tf
infrastructure-as-code/k8s-vault-config/outputs.tf
infrastructure-as-code/k8s-vault-config/variables.tf
self-serve-infrastructure/k8s-services/README.md
self-serve-infrastructure/k8s-services/main.tf

I updated the GKE version of the Terraform-Vault-k8s demo to run the pods and services in a provisioned cats-and-dogs namespace under a provisioned cats-and-dogs service account instead of running in the default namespace as was previously done.
I'm also now using the JWT token of a separate vault-reviewer service account which belongs to the default namespace when configuring the Vault Kubernetes auth method.  However, I could not do this in the original k8s-cluster-gke workspace because the Kubernetes provider tried to interpolate the values I passed to it from the created GKE cluster at the beginning of the run when they did not yet had values.
To work around this, I have shifted to using 3 workspaces:
1. k8s-cluster-gke to provision the Kubernetes cluster
2. k8s-vault-configuration to …

make GKE k8s demo use cats-and-dogs namespace and sa

---

.gitignore
operations/README.md
operations/automation-script/README.md
operations/automation-script/config/main.tf
operations/automation-script/deleteWorkspace.sh
operations/automation-script/loadAndRunWorkspace.sh
operations/automation-script/restrict-name-variable.sentinel
operations/automation-script/variables.csv
operations/sentinel-policies-scripts/README.md

I enhanced the loadAndRunWorkspace.sh script in several ways:
1. It now can clone Terraform code from a git repository. Before doing that, it deletes the existing directory that git will try to create.
2. It checks to see if the workspace already exists before trying to create it.
3. It names the tar file after the configuration directory containing the code which will be extracted from the git URL if one is provided.
4. It checks for a variables.csv file in the clone code and uses it if found.
I also added a deleteWorkspace.sh script to delete the workspace that the other script creates.

clone code from git repo and delete workspace

---

self-serve-infrastructure/k8s-services/main.tf
self-serve-infrastructure/k8s-services/variables.tf

I accidentally overrode changes that @grove-mountain had made last September to make it possible to use custom images for cats-and-dogs instead of my hard-coded images.  This PR restores those changes.  Apologies to Jake.

added custom image variables back

---

infrastructure-as-code/k8s-cluster-gke/variables.tf
infrastructure-as-code/k8s-vault-config/main.tf

minor fix to naming of Vault k8s auth method.  It is now set to <user>-<environment> in which latter defaults to "gke-dev" for GKE and "aks-dev" for AKS.

fixed naming of vault k8s auth method

---

infrastructure-as-code/k8s-cluster-openshift-aws/README.md
infrastructure-as-code/k8s-cluster-openshift-aws/main.tf

Changed to new command vault write aws-tf/roles/deploy policy_document=-<<EOF

Updated Ks Openshift Readme

---

governance/vmware/restrict-vm-cpu-and-memory.sentinel

Without explicitly specifying `int()` the following error occurs: `An error occurred: restrict-vm-cpu-and-memory.sentinel.sentinel:17:6: comparison requires both operands to be the same type, got string and int`  This PR fixes the issue. Tested in run-id: `run-BhfypMx1GjU11yBr`

added int type for cpu and memory comparison

---

README.md
operations/variable-scripts/README.md
operations/variable-scripts/delete-variables.sh
operations/variable-scripts/set-variables.sh

I modified variable scripts to require TFE_TOKEN and TFE_ORG environment variables be set. An optional TFE_ADDR variable can also be set, but it not the scripts will use app.terraform.io.
I also added second argument, run_from_set_variables, to delete-variables.sh which is only used (and set to "true") when it is called from set-variables.sh.  The purpose of this is to avoid redundant outputs related to the environment orgs when set-variables.sh does call delete-variables.sh.
Currently, the only editing of the script that would be needed before using would be to change `delete_first="false"` to `delete_first="true"` so that set-variables.sh will always call delete-variables.sh.  I did not set this to true in the script because I don't want anyone to accidentally delete variables when …

added env vars

---

operations/variable-scripts/README.md
operations/variable-scripts/delete-variables.sh
operations/variable-scripts/set-variables.sh

I added some logic so that the set-variables.sh script will call delete-variables.sh from the same directory that set-variables.sh lives in when the $delete_first variable  is set to "true".  This allows users to copy both scripts into a directory such as /usr/local/bin in their $PATH so that they can then run the scripts from that directory no matter what their current working directory is and make sure that set-variables.sh can find delete-variables.sh in the one added to the $PATH.  Previously, set-variables.sh would look for delete-variables.sh in the current working diretory.
If you simply clone the repository and run the scripts from operations/variable-scripts, the set-variables.sh script will find delete-variables.sh in that directory.  The same is true if you copy both scripts …

make scripts run from same directory

---

governance/second-generation/aws/enforce-mandatory-tags.sentinel
governance/second-generation/aws/require-private-acl-and-kms-for-s3-buckets.sentinel
governance/second-generation/aws/restrict-availability-zones.sentinel
governance/second-generation/aws/restrict-ec2-instance-type.sentinel
governance/second-generation/aws/restrict-ingress-sg-rule-cidr-blocks.sentinel
governance/second-generation/aws/restrict-launch-configuration-instance-type.sentinel
governance/second-generation/aws/test/enforce-mandatory-tags/fail.json
governance/second-generation/aws/test/enforce-mandatory-tags/mock-tfplan-fail.sentinel
governance/second-generation/aws/test/enforce-mandatory-tags/mock-tfplan-pass.sentinel
governance/second-generation/aws/test/enforce-mandatory-tags/pass.json
governance/second-generation/aws/test/restrict-availability-zones/fail.json
governance/second-generation/aws/test/restrict-availability-zones/mock-tfplan-fail.sentinel
governance/second-generation/aws/test/restrict-availability-zones/mock-tfplan-pass.sentinel
governance/second-generation/aws/test/restrict-availability-zones/pass.json
governance/second-generation/azure/restrict-app-service-to-https.sentinel
governance/second-generation/azure/restrict-vm-size.sentinel
governance/second-generation/gcp/restrict-gce-machine-type.sentinel
governance/second-generation/vmware/restrict-vm-cpu-and-memory.sentinel
governance/second-generation/vmware/restrict-vm-disk-size.sentinel

I added new new AWS policies in the new second generation style, enforce-mandatory-tags.sentinel and restrict-availability-zones.sentinel along with test cases for use with the Sentinel Simulator
Additionally, I revised all the second generation Sentinel policies that I had previously added as follows:
1. I removed names of policies from first line. It turns out that comments at the beginning of a Sentinel policy are shown in Sentinel output as the policy's description (ignoring the description added to the TF UI or by the TFE API or TFE provider).  Since the Sentinel output already gives the name of the policies, having them output again in the descriptions is redundant.
2. I removed some extraneous comments including some about things being printed since the Sentinel code made it clear …

two new AWS policies

---

governance/second-generation/aws/enforce-mandatory-tags.sentinel
governance/second-generation/aws/mocks/ec2-instance-mock-tfconfig.sentinel
governance/second-generation/aws/mocks/ec2-instance-mock-tfplan.sentinel
governance/second-generation/aws/mocks/ec2-instance-mock-tfstate.sentinel
governance/second-generation/aws/restrict-ec2-instance-type.sentinel
governance/second-generation/aws/test/restrict-ec2-instance-type/mock-tfplan-fail.sentinel
governance/second-generation/aws/test/restrict-ec2-instance-type/mock-tfplan-pass.sentinel
governance/second-generation/common-functions/find_resources_from_config.sentinel
governance/second-generation/common-functions/find_resources_from_plan.sentinel
governance/second-generation/common-functions/find_resources_from_state.sentinel
governance/second-generation/common-functions/validate_resource_attribute_in_list.sentinel

I've added some common Sentinel functions in a new governance/second-generation/common-functions directory:
* find_resources_from_plan() finds all resources of a specific type from all modules using the tfplan import. It is used in most of the second-generation policies in this repository.
* find_resources_from_config finds all resources of a specific type from all modules using the tfconfig import.
* find_resources_from_state finds all resources of a specific type from all modules using the tfstate import.
* validate_resource_attribute_in_list() validates that a specified top-level attribute in all resources of a specific type are in a specified list using the tfplan import. It uses the find_resources_from_plan() function. I will use this in at least one second-generation policy to …

Added some common Sentinel functions

---

infrastructure-as-code/k8s-cluster-gke/main.tf
self-serve-infrastructure/cats-and-dogs/backend/vote-db/start_redis.sh
self-serve-infrastructure/cats-and-dogs/frontend/azure-vote/main.py

Fixes GKE cluster to ensure that cert and key are generated.
Fixes cats-and-dogs application to add "/" in Vault path to adjust for change in output from Vault provider for auth backends that no longer includes the "/"

fixed GKE and c-&-d

---

infrastructure-as-code/terraform-0.12-examples/README.md
infrastructure-as-code/terraform-0.12-examples/advanced-dynamic-blocks/README.md
infrastructure-as-code/terraform-0.12-examples/advanced-dynamic-blocks/main.tf
infrastructure-as-code/terraform-0.12-examples/advanced-dynamic-blocks/terraform.tfvars

This adds an advanced dynamic block example for Terraform 0.12 which uses a variable that is a list of maps for determining the content of the dynamically generated blocks.  The specific example using the aws_elastic_beanstalk_environment resource had been asked about by a customer.

add advanced-dynamic-block TF 0.12 example

---

infrastructure-as-code/k8s-cluster-openshift-aws/README.md
infrastructure-as-code/k8s-cluster-openshift-aws/outputs.tf

Added master node's private IP so that someone can SSH from bastion. This is needed in case one wants to use the `oc` CLI to interact with OpenShift server.

added master private IP to outputs.tf

---

governance/second-generation/README.md
governance/second-generation/vmware/restrict-vm-cpu-and-memory.sentinel
governance/second-generation/vmware/restrict-vm-disk-size.sentinel

Fixed VMware policies to better handle Terraform 0.12 and nuances between Terraform 0.11 and 0.12.
Also added note to second-generation README.md warning that r.destroy is not yet available for PTFE and suggesting workarounds.

fix VMware policies for Terraform 0.12 and PTFE

---

governance/second-generation/README.md
governance/second-generation/aws/enforce-mandatory-tags.sentinel
governance/second-generation/aws/require-private-acl-and-kms-for-s3-buckets.sentinel
governance/second-generation/aws/restrict-availability-zones.sentinel
governance/second-generation/aws/restrict-db-instance-engines.sentinel
governance/second-generation/aws/restrict-ec2-instance-type.sentinel
governance/second-generation/aws/restrict-ingress-sg-rule-cidr-blocks.sentinel
governance/second-generation/aws/restrict-launch-configuration-instance-type.sentinel
governance/second-generation/azure/enforce-mandatory-tags.sentinel
governance/second-generation/azure/restrict-app-service-to-https.sentinel
governance/second-generation/azure/restrict-vm-size.sentinel
governance/second-generation/common-functions/plan/validate_attribute_contains_list.sentinel
governance/second-generation/common-functions/plan/validate_attribute_greater_than_value.sentinel
governance/second-generation/common-functions/plan/validate_attribute_has_value.sentinel
governance/second-generation/common-functions/plan/validate_attribute_in_list.sentinel
governance/second-generation/common-functions/plan/validate_attribute_less_than_value.sentinel
governance/second-generation/common-functions/plan/validate_attribute_matches_expression.sentinel
governance/second-generation/gcp/enforce-mandatory-labels.sentinel
governance/second-generation/gcp/restrict-gce-machine-type.sentinel
governance/second-generation/vmware/restrict-vm-cpu-and-memory.sentinel
governance/second-generation/vmware/restrict-vm-disk-size.sentinel

I had to change the condition that tests whether resources are being destroyed from `r.destroy` to `r.destroy and not r.requires_new` since `r.destroy` will be true when a resource is being temporarily destroyed and then re-created.  This happens when Terraform (actually the technology behind the provider) cannot modify certain attributes of an existing resource.  We don't want to skip these resources. We only want to skip the ones that are really being destroyed.
I updated all policies and functions that had the test that checked for resource destruction.
I also updated the second-generation README.md to explicitly refer to the improved condition.

add r.requires_new

---

infrastructure-as-code/dynamic-aws-creds/README.md
infrastructure-as-code/dynamic-aws-creds/consumer-workspace/main.tf
infrastructure-as-code/dynamic-aws-creds/producer-workspace/main.tf

This is a minor update, but is required to get this specific "dynamic-aws-creds" code working. 
**Change Overview:**
- Fixes to data objects to allow proper references (minor)
- Fixes to data objects with proper config syntax (minor)
- Fixes to `vault_aws_secret_backend_role` object with proper config syntax (minor)
- Fixes to AWS provider object with proper config syntax (minor)
**Tested Terraform Versions:**
- Terraform 12

This update includes fixes to a few resources that have been updated over time and require code updates.

---

governance/second-generation/aws/enforce-mandatory-tags.sentinel
governance/second-generation/azure/enforce-mandatory-tags.sentinel
governance/second-generation/gcp/enforce-mandatory-labels.sentinel

So, while my revised tags/labels policies for AWS, Azure, and GCP all work and pass all their test cases, while helping another SE with a much simpler policy, I determined that the attempt to convert `null` to `""` with the `else` operator was not working.  This was done in the test `r.applied[attribute] else "" is not ""`.  While the `else` operator converts `undefined` to the thing on its right, it does not convert `null`.
In my case, since I also had the condition `(types.type_of(r.applied[attribute]) is "list" or types.type_of(r.applied[attribute]) is "map")`, it did not matter that `null` was not converted to `""` since this additional test failed since `null` is neither a map nor a list.
But I don't want people to look at the code and think that they can convert `null` to something …

compare null to null

---

governance/second-generation/aws/restrict-ingress-sg-rule-cidr-blocks.sentinel
governance/second-generation/aws/test/require-private-acl-and-kms-for-s3-buckets/fail-kms-no-ssec-0.12.json
governance/second-generation/aws/test/require-private-acl-and-kms-for-s3-buckets/mock-tfplan-fail-kms-no-ssec-0.12.sentinel
governance/second-generation/aws/test/restrict-ingress-sg-rule-cidr-blocks/mock-tfplan-pass-no-cidr-blocks-0.12.sentinel
governance/second-generation/aws/test/restrict-ingress-sg-rule-cidr-blocks/pass-no-cidr-blocks-0.12.json
governance/second-generation/common-functions/plan/validate_attribute_contains_list.sentinel
governance/second-generation/common-functions/plan/validate_attribute_greater_than_value.sentinel
governance/second-generation/common-functions/plan/validate_attribute_less_than_value.sentinel
governance/second-generation/vmware/restrict-vm-cpu-and-memory.sentinel

After having improved tests for null in policies that test for tags/labels on VMs, I realized that I had neglected to do the same in three of the common functions.  So, I updated them to use the new test `r.applied[attribute] else null is not null`.  I also updated the restrict-vm-cpu-and-memory policy which uses the validate_attribute_less_than_value() function. Handling null cidr_blocks in aws_security_group_rules required a similar modification in the restrict-ingress-sg-rule-cidr-blocks policy.
Additionally, I added some additional test cases to check for the absence of server_side_encryption_configuration in aws_s3_buckets and for null cidr_blocks in aws_security_group_rules.  The first involved a new fail test case while the second involved a new pass test case.

better tests for null

---

governance/second-generation/cloud-agnostic/limit-proposed-monthly-cost.sentinel
governance/second-generation/cloud-agnostic/restrict-cost-and-percentage-increase.sentinel
governance/second-generation/cloud-agnostic/test/limit-proposed-monthly-cost/fail-0.12.json
governance/second-generation/cloud-agnostic/test/limit-proposed-monthly-cost/mock-tfrun-fail-0.12.sentinel
governance/second-generation/cloud-agnostic/test/limit-proposed-monthly-cost/mock-tfrun-pass-0.12.sentinel
governance/second-generation/cloud-agnostic/test/limit-proposed-monthly-cost/pass-0.12.json
governance/second-generation/cloud-agnostic/test/restrict-cost-and-percentage-increase/fail-limit-0.12.json
governance/second-generation/cloud-agnostic/test/restrict-cost-and-percentage-increase/fail-percent-increase-0.12.json
governance/second-generation/cloud-agnostic/test/restrict-cost-and-percentage-increase/mock-tfrun-fail-limit-0.12.sentinel
governance/second-generation/cloud-agnostic/test/restrict-cost-and-percentage-increase/mock-tfrun-fail-percent-increase-0.12.sentinel
governance/second-generation/cloud-agnostic/test/restrict-cost-and-percentage-increase/mock-tfrun-pass-0.12.sentinel
governance/second-generation/cloud-agnostic/test/restrict-cost-and-percentage-increase/pass-0.12.json

I added two policies that restrict provisioning based on the new cost estimates made available by the tfrun import. 
The limit-proposed-monthly-cost policy requires the run's `tfrun.cost_estimate.proposed_monthly_cost` to be less than the provided `limit` parameter.
The restrict-cost-and-percentage-increase policy imposes the same limit on `proposed_monthly_cost` as the other policy, but also requires the percentage increase in the proposed cost to be less than a `max_percent` parameter, but only if the run includes a non-zero value for `tfrun.cost_estimate.prior_monthly_cost` is not 0.  This is because a percentage increase cannot be computed against an initial cost of 0.
These policies also show the use of the new decimal import which was added for the purpose of doing accurate numeric …

added cost estimate policies

---

infrastructure-as-code/terraform-0.12-examples/README.md
infrastructure-as-code/terraform-0.12-examples/for-each-for-resources/README.md
infrastructure-as-code/terraform-0.12-examples/for-each-for-resources/main.tf

This addes new example under the infrastructure-as-code/terraform-0.12-examples directory that shows how to use the new `for_each` meta-argument that was added to resources in 0.12.6. It allows multiple instances of a single resource to be created based off data in a map or set in a different way than the `count` meta-argument supports.

new for_each for resources example

---

governance/second-generation/cloud-agnostic/limit-cost-by-workspace-type.sentinel
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/fail-dev-0.12.json
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/fail-other-0.12.json
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/fail-prod-0.12.json
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/fail-qa-0.12.json
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/mock-tfrun-fail-dev-0.12.sentinel
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/mock-tfrun-fail-other-0.12.sentinel
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/mock-tfrun-fail-prod-0.12.sentinel
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/mock-tfrun-fail-qa-0.12.sentinel
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/mock-tfrun-pass-dev-0.12.sentinel
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/mock-tfrun-pass-other-0.12.sentinel
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/mock-tfrun-pass-prod-0.12.sentinel
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/mock-tfrun-pass-qa-0.12.sentinel
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/pass-dev-0.12.json
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/pass-other-0.12.json
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/pass-prod-0.12.json
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/pass-qa-0.12.json

Add new cost estimate policy that sets different limits for different workspaces based on the workspace names, doing regex matching for names ending in "-dev", "-qa", and "-prod".  If a workspace name does not match one of those, it gets a lower limit.

add limit-cost-by-workspace-type

---

governance/second-generation/aws/restrict-assumed-role.sentinel
governance/second-generation/aws/test/restrict-assumed-role/fail-0.11.json
governance/second-generation/aws/test/restrict-assumed-role/fail-0.12.json
governance/second-generation/aws/test/restrict-assumed-role/mock-tfconfig-fail-0.11.sentinel
governance/second-generation/aws/test/restrict-assumed-role/mock-tfconfig-fail-0.12.sentinel
governance/second-generation/aws/test/restrict-assumed-role/mock-tfconfig-pass-0.11.sentinel
governance/second-generation/aws/test/restrict-assumed-role/mock-tfconfig-pass-0.12.sentinel
governance/second-generation/aws/test/restrict-assumed-role/mock-tfplan-fail-0.11.sentinel
governance/second-generation/aws/test/restrict-assumed-role/mock-tfplan-fail-0.12.sentinel
governance/second-generation/aws/test/restrict-assumed-role/mock-tfplan-pass-0.11.sentinel
governance/second-generation/aws/test/restrict-assumed-role/mock-tfplan-pass-0.12.sentinel
governance/second-generation/aws/test/restrict-assumed-role/pass-0.11.json
governance/second-generation/aws/test/restrict-assumed-role/pass-0.12.json
governance/second-generation/cloud-agnostic/test/validate-all-variables-have-descriptions/fail-0.11.json
governance/second-generation/cloud-agnostic/test/validate-all-variables-have-descriptions/fail-0.12.json
governance/second-generation/cloud-agnostic/test/validate-all-variables-have-descriptions/mock-tfconfig-fail-0.11.sentinel
governance/second-generation/cloud-agnostic/test/validate-all-variables-have-descriptions/mock-tfconfig-fail-0.12.sentinel
governance/second-generation/cloud-agnostic/test/validate-all-variables-have-descriptions/mock-tfconfig-pass-0.11.sentinel
governance/second-generation/cloud-agnostic/test/validate-all-variables-have-descriptions/mock-tfconfig-pass-0.12.sentinel
governance/second-generation/cloud-agnostic/test/validate-all-variables-have-descriptions/mock-tfplan-fail-0.11.sentinel
governance/second-generation/cloud-agnostic/test/validate-all-variables-have-descriptions/mock-tfplan-fail-0.12.sentinel
governance/second-generation/cloud-agnostic/test/validate-all-variables-have-descriptions/mock-tfplan-pass-0.11.sentinel
governance/second-generation/cloud-agnostic/test/validate-all-variables-have-descriptions/mock-tfplan-pass-0.12.sentinel
governance/second-generation/cloud-agnostic/test/validate-all-variables-have-descriptions/pass-0.11.json
governance/second-generation/cloud-agnostic/test/validate-all-variables-have-descriptions/pass-0.12.json
governance/second-generation/cloud-agnostic/validate-all-variables-have-descriptions.sentinel
governance/second-generation/common-functions/config/find_provider_aliases.md
governance/second-generation/common-functions/config/find_provider_aliases.sentinel
governance/second-generation/common-functions/config/find_variables_in_config.md
governance/second-generation/common-functions/config/find_variables_in_config.sentinel

I actually added two new policies and two functions as well as test cases that go with the policies.
The new policies are:
aws/restrict-assumed-role.sentinel
cloud-agnostic/validate-all-variables-have-descriptions.sentinel
The new functions are:
common-functions/config/find_provisioner_aliases.sentinel
common-functions/config/find_variables_in_config.sentinel
The functions have corresponding `*.md` files that describe them.

Add restrict assumed role policy

---

governance/second-generation/aws/restrict-ingress-sg-rule-cidr-blocks.sentinel
governance/second-generation/aws/test/restrict-ingress-sg-rule-cidr-blocks/mock-tfplan-fail-0.11.sentinel
governance/second-generation/aws/test/restrict-ingress-sg-rule-cidr-blocks/mock-tfplan-fail-0.12.sentinel
governance/second-generation/aws/test/restrict-ingress-sg-rule-cidr-blocks/mock-tfplan-pass-0.11.sentinel
governance/second-generation/aws/test/restrict-ingress-sg-rule-cidr-blocks/mock-tfplan-pass-0.12.sentinel
governance/second-generation/aws/test/restrict-ingress-sg-rule-cidr-blocks/mock-tfplan-pass-no-cidr-blocks-0.12.sentinel

In response to a customer request, I've modified the AWS policy that restricts security group rules, restrict-ingress-sg-rule-cidr-blocks.sentinel, that previously only looked at aws_security_group_rule resources to also examine aws_security_group resources.
I've also modified some the mocks used to test this policy to include a security group.

Restrict aws sgs

---

governance/second-generation/cloud-agnostic/blacklist-resources.sentinel
governance/second-generation/cloud-agnostic/test/blacklist-resources/fail-0.12.json
governance/second-generation/cloud-agnostic/test/blacklist-resources/mock-tfplan-fail-0.12.sentinel
governance/second-generation/cloud-agnostic/test/blacklist-resources/mock-tfplan-pass-0.12.sentinel
governance/second-generation/cloud-agnostic/test/blacklist-resources/pass-0.12.json

The requirement for this policy is to restrict a workspace from making any type of changes to a list of resources.

Adding blacklist-resources sentinel policy

---

governance/second-generation/README.md
governance/second-generation/aws/sentinel.hcl
governance/second-generation/azure/sentinel.hcl
governance/second-generation/cloud-agnostic/sentinel.hcl
governance/second-generation/gcp/sentinel.hcl
governance/second-generation/vmware/sentinel.hcl

Adding policy set declaration files for each cloud and also for the cloud-agnostic directory of policies.
Also updated second-generation README.md to describe the policy sets and to indicate that when new policies are added, they should be listed in the policy sets.

add policy set declarations

---

governance/second-generation/cloud-agnostic/prevent-non-root-providers.sentinel
governance/second-generation/cloud-agnostic/test/prevent-non-root-providers/fail-0.11.json
governance/second-generation/cloud-agnostic/test/prevent-non-root-providers/fail-0.12.json
governance/second-generation/cloud-agnostic/test/prevent-non-root-providers/mock-tfconfig-fail-0.11.sentinel
governance/second-generation/cloud-agnostic/test/prevent-non-root-providers/mock-tfconfig-fail-0.12.sentinel
governance/second-generation/cloud-agnostic/test/prevent-non-root-providers/mock-tfconfig-pass-0.11.sentinel
governance/second-generation/cloud-agnostic/test/prevent-non-root-providers/mock-tfconfig-pass-0.12.sentinel
governance/second-generation/cloud-agnostic/test/prevent-non-root-providers/pass-0.11.json
governance/second-generation/cloud-agnostic/test/prevent-non-root-providers/pass-0.12.json

I've added a new policy called prevent-non-root-providers.sentinel and associated test cases and mocks to prevent any providers from being declared in non-root modules.  This is to allow customers to enforce our best practices in https://www.terraform.io/docs/configuration/modules.html#providers-within-modules

added prevent-non-root-providers.sentinel

---

governance/second-generation/cloud-agnostic/limit-cost-by-workspace-type.sentinel
governance/second-generation/cloud-agnostic/limit-proposed-monthly-cost.sentinel
governance/second-generation/cloud-agnostic/restrict-cost-and-percentage-increase.sentinel
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/mock-tfrun-pass-no-estimates-0.12.sentinel
governance/second-generation/cloud-agnostic/test/limit-cost-by-workspace-type/pass-no-estimates-0.12.json
governance/second-generation/cloud-agnostic/test/limit-proposed-monthly-cost/mock-tfrun-pass-no-estimates-0.12.sentinel
governance/second-generation/cloud-agnostic/test/limit-proposed-monthly-cost/pass-no-estimates-0.12.json
governance/second-generation/cloud-agnostic/test/restrict-cost-and-percentage-increase/mock-tfrun-pass-no-estimates-0.12.sentinel
governance/second-generation/cloud-agnostic/test/restrict-cost-and-percentage-increase/pass-no-estimates-0.12.json

Cost estimates are only available for Terraform 0.12.
In theory, customers should only use policies that check costimates against workspaces that are configured to use Terraform 0.12.
However, if they set up a policy set to work against all workspaces including some that are using Terraform 0.11, we don't want the cost estimate policies to give hard Sentinel failures.
The revised policies now test whether tfrun.cost_estimate is undefined.  If so, it prints out a message saying "No cost estimates available" and returns true, allowing the policy to pass.

fix cost policies for no cost_estimate

---

infrastructure-as-code/k8s-cluster-openshift-aws/README.md
infrastructure-as-code/k8s-cluster-openshift-aws/main.tf

This PR works around issue with Ansible playbook that installs the OpenShift cluster taking too long and causing the Vault token generated by the Vault provider to time out and the apply to fail.  My original idea was to add a second copy of the null_resource "get_config" that could be used on a second apply to finish the deployment and get the outputs.  And that actually did work.  But I then remembered that I could increase the `max_lease_ttl_seconds` attribute of the Vault provider from 1 hour to 2 hours.  This allows the first apply to succeed and give outputs.

Get config 2 openshift

---

governance/second-generation/aws/restrict-ami-owners.sentinel
governance/second-generation/aws/test/restrict-ami-owners/fail-0.11.json
governance/second-generation/aws/test/restrict-ami-owners/fail-0.12.json
governance/second-generation/aws/test/restrict-ami-owners/mock-tfstate-fail-0.11.sentinel
governance/second-generation/aws/test/restrict-ami-owners/mock-tfstate-fail-0.12.sentinel
governance/second-generation/aws/test/restrict-ami-owners/mock-tfstate-pass-0.11.sentinel
governance/second-generation/aws/test/restrict-ami-owners/mock-tfstate-pass-0.12.sentinel
governance/second-generation/aws/test/restrict-ami-owners/pass-0.11.json
governance/second-generation/aws/test/restrict-ami-owners/pass-0.12.json
governance/second-generation/azure/restrict-publishers-of-current-vms.sentinel
governance/second-generation/common-functions/state/find_datasources_from_state.md
governance/second-generation/common-functions/state/find_datasources_from_state.sentinel
governance/second-generation/common-functions/state/find_resources_from_state.sentinel

This adds a second generation version of the first-generation policy enforce-ami-owners.sentinel, but I have called it restrict-ami-owners.sentinel to better align with naming of other policies.
It restricts all instances of the aws_ami data source to have owners in a specified list.
I have also updated the find_datasources_from_state and find_resources_from_state functions to use `for tfstate.module_paths else [] as path` to handle the case that the current state is empty.

Add enforce ami owners

---

governance/second-generation/cloud-agnostic/test/whitelist-resources/fail-0.12.json
governance/second-generation/cloud-agnostic/test/whitelist-resources/mock-tfplan-fail-0.12.sentinel
governance/second-generation/cloud-agnostic/test/whitelist-resources/mock-tfplan-pass-0.12.sentinel
governance/second-generation/cloud-agnostic/test/whitelist-resources/pass-0.12.json
governance/second-generation/cloud-agnostic/whitelist-resources.sentinel
governance/second-generation/common-functions/plan/find_resource_types_from_plan.md
governance/second-generation/common-functions/plan/find_resource_types_from_plan.sentinel

This adds a whitelist-resources.sentinel policy that only allows resources from the given whitelist to be provisioned.

add whitelist-resources.sentinel policy

---

governance/first-generation/gcp/block-allow-all-cidr.sentinel

Fix first-generation Sentinel policy for GCP: block-allow-all-cidr.sentinel to support multiple ranges in source_ranges and to check that source_ranges actually exists (and has length > 0)

support multiple source_ranges

---

governance/second-generation/gcp/enforce-mandatory-labels.sentinel

Google's arbitrary key/value pairs attached to resources are called labels.  Let's not use the word tags in this Sentinel policy because it could be confusing to users. In GCP land, tags are a list of regexes for enabling firewall rules.

Make labels consistent

---

governance/second-generation/cloud-agnostic/limit-proposed-monthly-cost.sentinel

Thanks Roger I've been working with partners in Europe and it's important for them to know which currency they're working with.  Cost estimation is always in USD$ afaik.  Just a suggestion.

Suggest adding currency symbol.

---

governance/third-generation/README.md
governance/third-generation/aws/enforce-mandatory-tags.sentinel
governance/third-generation/aws/require-private-acl-and-kms-for-s3-buckets.sentinel
governance/third-generation/aws/restrict-current-ec2-instance-type.sentinel
governance/third-generation/aws/restrict-ec2-instance-type.sentinel
governance/third-generation/aws/test/enforce-mandatory-tags/fail.json
governance/third-generation/aws/test/enforce-mandatory-tags/pass.json
governance/third-generation/aws/test/require-private-acl-and-kms-for-s3-buckets/fail-acl-and-kms.json
governance/third-generation/aws/test/require-private-acl-and-kms-for-s3-buckets/fail-kms.json
governance/third-generation/aws/test/require-private-acl-and-kms-for-s3-buckets/fail-no-ssec.json
governance/third-generation/aws/test/require-private-acl-and-kms-for-s3-buckets/pass.json
governance/third-generation/aws/test/restrict-current-ec2-instance-type/fail.json
governance/third-generation/aws/test/restrict-current-ec2-instance-type/pass.json
governance/third-generation/aws/test/restrict-ec2-instance-type/fail.json
governance/third-generation/aws/test/restrict-ec2-instance-type/pass.json
governance/third-generation/azure/restrict-vm-size.sentinel
governance/third-generation/azure/test/restrict-vm-size/fail.json
governance/third-generation/azure/test/restrict-vm-size/pass.json
governance/third-generation/gcp/restrict-gce-machine-type.sentinel
governance/third-generation/gcp/test/restrict-gce-machine-type/fail.json
governance/third-generation/gcp/test/restrict-gce-machine-type/pass.json
governance/third-generation/vmware/restrict-vm-cpu-and-memory.sentinel
governance/third-generation/vmware/test/restrict-vm-cpu-and-memory/fail-cpu-and-memory.json
governance/third-generation/vmware/test/restrict-vm-cpu-and-memory/fail-cpu.json
governance/third-generation/vmware/test/restrict-vm-cpu-and-memory/fail-memory.json
governance/third-generation/vmware/test/restrict-vm-cpu-and-memory/pass.json

I decided to change the names of the custom Sentinel imports as defined in the test case files to match the names of the files containing them (without the .sentinel extension).
I then use import aliases to get back to using the short names like "plan" and "state".
So, the import statements look like this:
```
import "tfplan-functions" as plan
```
or
```
import "tfstate-functions" as state
```
This should avoid possible confusion with the tfplan/v2 and tfstate/v2 imports and also make clear what sentinel import file contains the functions of the import.
But it still keeps lines that use the custom functions short.

change names of custom imports and use aliases

---

governance/third-generation/README.md

Update the README.md in governance/third-generation to indicate that Sentinel Modules are now usable in TFC but that one needs to put modules under the VCS directory with the sentinel.hcl file.

update 3gen README.md about using with TFC

---

infrastructure-as-code/k8s-cluster-openshift-aws/README.md
self-serve-infrastructure/k8s-services-openshift/README.md
self-serve-infrastructure/k8s-services-openshift/main.tf

Kubernetes provider 1.11.x and higher now need `load_config_file = false` in the kubernetes provider block if using statically defined credentials.  See https://www.terraform.io/docs/providers/kubernetes/index.html#statically-defined-credentials
Additionallly It turned out that the change @kawsark  had made in commit f0c78c2 required using Vault server 1.2 or higher.  So, I updated relevant README.md files to say that.

use load_config_file = false in k8s provider

---

governance/third-generation/aws/sentinel.hcl

I had forgotten to add the aws-functions Sentinel module to the sentinel.hcl policy set file under the aws directory.

added aws-functions module to aws policy set

---

governance/third-generation/README.md
governance/third-generation/aws/aws-functions/aws-functions.sentinel
governance/third-generation/aws/aws-functions/docs/find_resources_with_standard_tags.md
governance/third-generation/aws/enforce-mandatory-tags.sentinel
governance/third-generation/aws/test/enforce-mandatory-tags/fail.json
governance/third-generation/aws/test/enforce-mandatory-tags/mock-tfconfig-fail.sentinel
governance/third-generation/aws/test/enforce-mandatory-tags/mock-tfconfig-pass.sentinel
governance/third-generation/aws/test/enforce-mandatory-tags/mock-tfplan-fail.sentinel
governance/third-generation/aws/test/enforce-mandatory-tags/mock-tfplan-pass.sentinel
governance/third-generation/aws/test/enforce-mandatory-tags/pass.json
governance/third-generation/common-functions/tfplan-functions/docs/find_datasources_by_provider.md
governance/third-generation/common-functions/tfplan-functions/docs/find_resources_by_provider.md
governance/third-generation/common-functions/tfplan-functions/tfplan-functions.sentinel
governance/third-generation/common-functions/tfstate-functions/docs/find_datasources_by_provider.md
governance/third-generation/common-functions/tfstate-functions/docs/find_resources_by_provider.md
governance/third-generation/common-functions/tfstate-functions/tfstate-functions.sentinel

I've added the following new common functions:
tfstate-functions: find_datasources_by_provider and find_resources_by_provider
tfplan-functions: find_datasources_by_provider and find_resources_by_provider
aws-functions: find_resources_with_standard_tags
Also, I updated the AWS enforce-mandatory-tags.sentinel policy to use the new find_resources_with_standard_tags function and expanded the test case to include an S3 bucket in addition to the EC2 instances that it previously included.

add some more common functions

---

governance/third-generation/cloud-agnostic/http-examples/README.md
governance/third-generation/cloud-agnostic/http-examples/sentinel.hcl

I fixed the instructions for testing the http import example policies in TFC, removing the reference to a personal repo that had a copy of the second-gen version of use-latest-module-versions.sentinel.  I also removed asteroids.sentinel from sentinel.hcl so that I would not have to document how to define parameters for it when registering the policy set.

fix instructions for using in TFC

---

governance/first-generation/README.md
governance/second-generation/README.md
governance/third-generation/README.md
governance/third-generation/aws/sentinel.hcl
governance/third-generation/azure/sentinel.hcl
governance/third-generation/cloud-agnostic/http-examples/sentinel.hcl
governance/third-generation/cloud-agnostic/sentinel.hcl
governance/third-generation/gcp/sentinel.hcl
governance/third-generation/vmware/sentinel.hcl

I've added a source to every policy in each instance of sentinel.hcl in the third-generation policies. While this is not needed at this time, it will be required in the future and I wanted to avoid problems.
Also, I updated the first, second, and third-generation README.md files.  This includes pointing out that the common functions can now be used by TFC policy sets as currently organized and that this will also be possible in TFE starting with the next release targeted for the end of June.

add source to all policies in sets

---

governance/third-generation/cloud-agnostic/sentinel.hcl

Had changed name of a policy that limits cost by workspace names, but had not updated sentinel.hcl

fix cloud-agnostic sentinel.hcl

---

governance/third-generation/README.md

I updated the third-gen README.md to indicate that TFE v202006-1 now fully supports the third-generation Sentinel policies as organized (meaning that modules that are not under the directory containing sentinel.hcl can be referenced using ../ notation).

TFE v202006-1 fully supports third-gen sentinel policies

---

governance/third-generation/aws/require-dns-support-for-vpcs.sentinel
governance/third-generation/aws/require-vpc-and-kms-for-lambda-functions.sentinel
governance/third-generation/aws/test/require-dns-support-for-vpcs/fail-dns-hostnames.json
governance/third-generation/aws/test/require-dns-support-for-vpcs/fail-dns-support.json
governance/third-generation/aws/test/require-dns-support-for-vpcs/fail-vpc-support-and-hostnames.json
governance/third-generation/aws/test/require-dns-support-for-vpcs/mock-tfplan-fail-dns-hostnames.sentinel
governance/third-generation/aws/test/require-dns-support-for-vpcs/mock-tfplan-fail-dns-support-and-hostnames.sentinel
governance/third-generation/aws/test/require-dns-support-for-vpcs/mock-tfplan-fail-dns-support.sentinel
governance/third-generation/aws/test/require-dns-support-for-vpcs/mock-tfplan-pass.sentinel
governance/third-generation/aws/test/require-dns-support-for-vpcs/pass.json
governance/third-generation/aws/test/require-vpc-and-kms-for-lambda-functions/fail-kms.json
governance/third-generation/aws/test/require-vpc-and-kms-for-lambda-functions/fail-vpc-and-kms.json
governance/third-generation/aws/test/require-vpc-and-kms-for-lambda-functions/fail-vpc.json
governance/third-generation/aws/test/require-vpc-and-kms-for-lambda-functions/mock-tfplan-fail-kms.sentinel
governance/third-generation/aws/test/require-vpc-and-kms-for-lambda-functions/mock-tfplan-fail-vpc-and-kms.sentinel
governance/third-generation/aws/test/require-vpc-and-kms-for-lambda-functions/mock-tfplan-fail-vpc.sentinel
governance/third-generation/aws/test/require-vpc-and-kms-for-lambda-functions/mock-tfplan-pass.sentinel
governance/third-generation/aws/test/require-vpc-and-kms-for-lambda-functions/pass.json
governance/third-generation/common-functions/tfconfig-functions/tfconfig-functions.sentinel
governance/third-generation/common-functions/tfplan-functions/tfplan-functions.sentinel
governance/third-generation/common-functions/tfstate-functions/tfstate-functions.sentinel

This migrates two first-generation Sentinel policies to third-generation:
* require-dns-support-for-vpcs.sentinel
* require-vpc-and-kms-for-lambda-functions.sentinel
It also fixes a minor bug in the to_string() functions of the common functions so that it will now convert an empty list to "[]" instead of to "[".

migrate 2 gen1 policies to gen3

---

governance/third-generation/aws/restrict-ec2-instance-type.sentinel
governance/third-generation/azure/restrict-vm-size.sentinel
governance/third-generation/gcp/restrict-gce-machine-type.sentinel

I want to count the violations in some of the prototypical third-generation policies before the main rule to better match what I do in the Sentinel for Terraform workshop.

count violations before main rule

---

governance/third-generation/cloud-agnostic/evaluate-variables-in-nested-modules.sentinel
governance/third-generation/cloud-agnostic/prohibited-local-exec-commands.sentinel
governance/third-generation/cloud-agnostic/test/evaluate-variables-in-nested-modules/mock-tfconfig-pass.sentinel
governance/third-generation/cloud-agnostic/test/evaluate-variables-in-nested-modules/pass.json
governance/third-generation/cloud-agnostic/test/prohibited-local-exec-commands/fail-constant-value.json
governance/third-generation/cloud-agnostic/test/prohibited-local-exec-commands/fail-reference.json
governance/third-generation/cloud-agnostic/test/prohibited-local-exec-commands/mock-tfconfig-fail-constant-value.sentinel
governance/third-generation/cloud-agnostic/test/prohibited-local-exec-commands/mock-tfconfig-fail-reference.sentinel
governance/third-generation/cloud-agnostic/test/prohibited-local-exec-commands/mock-tfconfig-pass.sentinel
governance/third-generation/cloud-agnostic/test/prohibited-local-exec-commands/pass.json
governance/third-generation/common-functions/tfconfig-functions/tfconfig-functions.sentinel

This improves regex in the tfconfig-functions.sentinel module on the advice of a customer who gave me better regex.
I also added two new cloud-agnostic policies that I wrote some time ago but never committed:
1. evaluate-variables-in-nested-modules.sentinel shows how to evaluate variables passed to modules in module calls.  It currently only evaluated constant values that are passed, but does print references if those are used without attempting to evaluate their values.  I might add that in the future. The policy always returns true. It is not really a policy but more of a policy snippet that could be used in other policies that did want to restrict the values of variables passed to modules.
2. prohibited-local-exec-commands.sentinel prevents certain commands from being used in …

Improve regex

---

governance/third-generation/README.md
governance/third-generation/aws/require-most-recent-AMI-version.sentinel
governance/third-generation/aws/test/require-most-recent-AMI-version/fail.json
governance/third-generation/aws/test/require-most-recent-AMI-version/mock-tfconfig-fail.sentinel
governance/third-generation/aws/test/require-most-recent-AMI-version/mock-tfconfig-pass.sentinel
governance/third-generation/aws/test/require-most-recent-AMI-version/mock-tfstate-fail.sentinel
governance/third-generation/aws/test/require-most-recent-AMI-version/mock-tfstate-pass.sentinel
governance/third-generation/aws/test/require-most-recent-AMI-version/pass.json
governance/third-generation/common-functions/tfconfig-functions/docs/evaluate_attribute.md
governance/third-generation/common-functions/tfconfig-functions/docs/filter_attribute_does_not_match_regex.md
governance/third-generation/common-functions/tfconfig-functions/docs/filter_attribute_matches_regex.md
governance/third-generation/common-functions/tfconfig-functions/tfconfig-functions.sentinel
governance/third-generation/common-functions/tfplan-functions/docs/filter_attribute_contains_items_from_list.md
governance/third-generation/common-functions/tfplan-functions/docs/filter_attribute_contains_items_not_in_list.md
governance/third-generation/common-functions/tfplan-functions/docs/filter_attribute_in_list.md
governance/third-generation/common-functions/tfplan-functions/docs/filter_attribute_is_value.md
governance/third-generation/common-functions/tfplan-functions/docs/filter_attribute_matches_regex.md
governance/third-generation/common-functions/tfplan-functions/docs/filter_attribute_not_in_list.md
governance/third-generation/common-functions/tfplan-functions/tfplan-functions.sentinel
governance/third-generation/common-functions/tfstate-functions/docs/filter_attribute_contains_items_from_list.md
governance/third-generation/common-functions/tfstate-functions/docs/filter_attribute_contains_items_not_in_list.md
governance/third-generation/common-functions/tfstate-functions/docs/filter_attribute_in_list.md
governance/third-generation/common-functions/tfstate-functions/docs/filter_attribute_is_value.md
governance/third-generation/common-functions/tfstate-functions/docs/filter_attribute_matches_regex.md
governance/third-generation/common-functions/tfstate-functions/docs/filter_attribute_not_in_list.md
governance/third-generation/common-functions/tfstate-functions/tfstate-functions.sentinel

Added require-most-recent-AMI-version.sentinel policy
Also added new regex matching function in tfconfig-functions module and evaluate_attribute() function that they use.
I aldo updated some of the tfplan-functions and tfstate-functions functions to handle null differently.
And I updated the corresponding docs for the functions.

add require-most-recent-AMI-version policy

---

governance/third-generation/aws/aws-functions/aws-functions.sentinel

change description of provider parameter in filter_resources_by_region() function in aws-functions .sentinel.  I had said it should be a string like "aws", but it actually has to be an actual instance of a provider from tfconfig.providers.
https://github.com/hashicorp/terraform-guides/blob/master/governance/third-generation/aws/aws-functions/docs/filter_resources_by_region.md was already correct.

minor fix in comment on filter_resources_by_region

---

governance/third-generation/aws/aws-functions/aws-functions.sentinel
governance/third-generation/aws/aws-functions/docs/filter_resources_by_region.md
governance/third-generation/aws/validate-resources-from-desired-regions.sentinel

This simplifies the validate-resources-from-desired-regions policy and the filter_resources_by_region() function it calls to remove use of provider loop in the first and passing of provider to the second.

improve validate-resources-from-desired-regions

---

governance/third-generation/aws/require-vpc-and-kms-for-lambda-functions.sentinel
governance/third-generation/azure/restrict-publishers-of-current-vms.sentinel
governance/third-generation/common-functions/tfplan-functions/docs/find_datasources.md
governance/third-generation/common-functions/tfplan-functions/docs/find_datasources_by_provider.md
governance/third-generation/common-functions/tfplan-functions/docs/find_resources.md
governance/third-generation/common-functions/tfplan-functions/docs/find_resources_by_provider.md
governance/third-generation/common-functions/tfplan-functions/tfplan-functions.sentinel

I decided that the tfplan-functions module find functions should actually find all resources that are not being permanently deleted.  So, I changed the find functions to use the following actions condition:
```
rc.change.actions contains "create" or rc.change.actions contains "update" or
rc.change.actions contains "read" or rc.change.actions contains "no-op"
```
Previously, it had been:
```
rc.change.actions contains "create" or rc.change.actions contains "update"
```
I also updated docs for the related functions which are find_datasources_by_provider, find_datasources, find_resources_by_provider and find_resources.

Include read and no op actions

---

operations/automation-script/README.md
operations/automation-script/loadAndRunWorkspace.sh
operations/automation-script/variables.csv

I updated the loadAndRunWorkspace.sh script to handle more run and apply statuses.
I also added a comment to explain why is_confirmable is checked against "True" instead of "true" (because Python converts boolean `true`in JSON response  to `True`.

handle more run and apply statuses

---

governance/third-generation/cloud-agnostic/prevent-non-root-providers.sentinel
governance/third-generation/cloud-agnostic/test/prevent-non-root-providers/mock-tfconfig-fail.sentinel
governance/third-generation/cloud-agnostic/test/prevent-non-root-providers/mock-tfconfig-pass.sentinel

I improved the prevent-non-root-providers.sentinel policy to allow provider proxy configuration blocks that only have a name and alias to a provider in the calling module.  See https://www.terraform.io/docs/modules/providers.html#proxy-configuration-blocks

allow proxy config blocks for providers

---

governance/third-generation/README.md
governance/third-generation/aws/aws-functions/aws-functions.sentinel
governance/third-generation/aws/aws-functions/docs/find_resources_with_standard_tags.md
governance/third-generation/aws/enforce-mandatory-tags.sentinel
governance/third-generation/azure/azure-functions/azure-functions.sentinel
governance/third-generation/azure/azure-functions/docs/find_resources_with_standard_tags.md
governance/third-generation/azure/enforce-mandatory-tags.sentinel
governance/third-generation/azure/test/enforce-mandatory-tags/fail.hcl
governance/third-generation/azure/test/enforce-mandatory-tags/pass.hcl

This PR adds a new module, azure-functions with the function find_resources_with_standard_tags() that can be used to find all Azure resources of specified types.  The intention as indicated by the name is to find Azure resources that should have tags.
It also updates the corresponding function in the aws-functions module to only require tags in a given list of AWS resources instead of requiring tags for all resources not in a given list.  This change was made since I determined that there are more AWS resources that do not have tags than I previously thought.
I also updated the docs for the two functions.
The AWS and Azure enforce-mandatory-tags.sentinel policies have both been updated to use the new/modified functions.
The test cases for the Azure enforce-mandatory-tags.sentinel policy …

update enforce-mandatory-tags policies

---

governance/third-generation/aws/restrict-sagemaker-notebooks.sentinel
governance/third-generation/aws/test/restrict-sagemaker-notebooks/fail-direct-internet-access.hcl
governance/third-generation/aws/test/restrict-sagemaker-notebooks/fail-missing-values.hcl
governance/third-generation/aws/test/restrict-sagemaker-notebooks/fail-root-access.hcl
governance/third-generation/aws/test/restrict-sagemaker-notebooks/fail-root-and-internet-access.hcl
governance/third-generation/aws/test/restrict-sagemaker-notebooks/mock-tfplan-fail-direct-internet.sentinel
governance/third-generation/aws/test/restrict-sagemaker-notebooks/mock-tfplan-fail-missing-values.sentinel
governance/third-generation/aws/test/restrict-sagemaker-notebooks/mock-tfplan-fail-root-access.sentinel
governance/third-generation/aws/test/restrict-sagemaker-notebooks/mock-tfplan-fail-root-and-internet-access.sentinel
governance/third-generation/aws/test/restrict-sagemaker-notebooks/mock-tfplan-pass.sentinel
governance/third-generation/aws/test/restrict-sagemaker-notebooks/pass.hcl
governance/third-generation/common-functions/tfplan-functions/tfplan-functions.sentinel

This adds a Sentinel policy to restrict certain attributes (root_access and direct_internet_access) of Sagemaker notebook instances.

add restrict-sagemaker-notebooks.sentinel

---

governance/third-generation/aws/restrict-s3-bucket-policies.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/fail-bucket-policy.hcl
governance/third-generation/aws/test/restrict-s3-bucket-policies/fail-bucket.hcl
governance/third-generation/aws/test/restrict-s3-bucket-policies/fail-invalid-vpces.hcl
governance/third-generation/aws/test/restrict-s3-bucket-policies/fail-missing-vpce.hcl
governance/third-generation/aws/test/restrict-s3-bucket-policies/fail-secure-transport.hcl
governance/third-generation/aws/test/restrict-s3-bucket-policies/mock-tfconfig-fail-bucket-policy.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/mock-tfconfig-fail-bucket.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/mock-tfconfig-fail-invalid-vpces.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/mock-tfconfig-fail-missing-vpce.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/mock-tfconfig-fail-secure-transport.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/mock-tfconfig-pass.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/mock-tfplan-fail-bucket-policy.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/mock-tfplan-fail-bucket.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/mock-tfplan-fail-invalid-vpces.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/mock-tfplan-fail-missing-vpce.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/mock-tfplan-fail-secure-transport.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/mock-tfplan-pass.sentinel
governance/third-generation/aws/test/restrict-s3-bucket-policies/pass.hcl
governance/third-generation/common-functions/tfconfig-functions/tfconfig-functions.sentinel

This adds a Sentinel policy that restricts the policies applied to S3 buckets so that they must be defined in an aws_iam_policy_document data source and that that any policy document that applies to a list of S3 actions must include statements with conditions that prevent HTTP access and mandate acess from specific VPC endpoints.

add restrict-s3-bucket-policies.sentinel policy

---

governance/third-generation/aws/restrict-ingress-sg-rule-rdp.sentinel
governance/third-generation/aws/restrict-ingress-sg-rule-ssh.sentinel
governance/third-generation/aws/sentinel.hcl
governance/third-generation/aws/test/restrict-ingress-sg-rule-rdp/fail.hcl
governance/third-generation/aws/test/restrict-ingress-sg-rule-rdp/mock-tfplan-fail.sentinel
governance/third-generation/aws/test/restrict-ingress-sg-rule-rdp/mock-tfplan-pass.sentinel
governance/third-generation/aws/test/restrict-ingress-sg-rule-rdp/pass.hcl
governance/third-generation/aws/test/restrict-ingress-sg-rule-ssh/fail.hcl
governance/third-generation/aws/test/restrict-ingress-sg-rule-ssh/mock-tfplan-fail.sentinel
governance/third-generation/aws/test/restrict-ingress-sg-rule-ssh/mock-tfplan-pass.sentinel
governance/third-generation/aws/test/restrict-ingress-sg-rule-ssh/pass.hcl
governance/third-generation/common-functions/tfplan-functions/tfplan-functions.sentinel

Created new 3rd Gen policies for restricting SSH and RDP. They have similar targeting as terraform-foundational-policies-library/cis/aws/networking/aws-cis-4.2-networking-deny-public-rdp-acl-rules and terraform-foundational-policies-library/cis/aws/networking/aws-cis-4.1-networking-deny-public-ssh-acl-rules but adds "read" and "no-op" to resource changes, loops through both the aws_security_group and the aws_security_group_rule resources, and provides greater detail of violations.
Two new policy sets were added:
restrict-ingress-sg-rule-rdp
restrict-ingress-sg-rule-ssh
Changes were made to:
tfplan-function - adding "filter_attribute_less_than_equal_to_value" and "filter_attribute_greater_than_equal_to_value".

Two new policies restricting SSH and RDP for 0.0.0.0/0 for AWS SGs

---

governance/third-generation/aws/sentinel.hcl
governance/third-generation/azure/sentinel.hcl
governance/third-generation/cloud-agnostic/sentinel.hcl
governance/third-generation/gcp/sentinel.hcl
governance/third-generation/vmware/sentinel.hcl

I realized that I have neglected to add many recently added policies to their corresponding sentinel.hcl policy set definition files.  This PR adds them all and puts them in alphabetical order to make it easier to check for missing policies in them in the future.

update sentinel.hcl files to add policies

---

operations/sentinel-policies-scripts/policy-set/restrict-s3-bucket-policies.sentinel
operations/sentinel-policies-scripts/policy-set/sentinel.hcl

I had an incorrect label for the sagemaker policy in the example sentinel.hcl file in the policy-set directory associated with the new create-policy-set-version.sh script.  I fixed that and also added the tfconfig-functions module and a second policy that uses both it and the tfplan-functions module that was already included in sentinel.hcl.

improve policy-set example for script

---

infrastructure-as-code/s3-buckets-and-policies/README.md
infrastructure-as-code/s3-buckets-and-policies/main.tf
infrastructure-as-code/sagemaker-notebook/README.md
infrastructure-as-code/sagemaker-notebook/main.tf

This adds Terraform code that I used to generate Sentinel mocks for two Sentinel policies. See the README.md files for details.

add Terraform code for two Sentinel policies

---

governance/third-generation/aws/aws-functions/aws-functions.sentinel
governance/third-generation/aws/restrict-s3-bucket-policies.sentinel
governance/third-generation/cloud-agnostic/restrict-resources-by-module-source.sentinel
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/fail.hcl
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/mock-tfconfig-fail.sentinel
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/mock-tfconfig-pass.sentinel
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/pass.hcl
governance/third-generation/common-functions/tfconfig-functions/docs/find_descendant_modules.md
governance/third-generation/common-functions/tfconfig-functions/docs/get_module_source.md
governance/third-generation/common-functions/tfconfig-functions/tfconfig-functions.sentinel

This adds a new restrict-resources-by-modules-source.sentinel poilcy that restricts resources of specific types to only be created in modules with sources in a given list. It used the tfconfig/v2 import and a new function, get_module_source(), that I added to the tfconfig-functions.sentinel module. There is a new MD file to describe that new function.
It also fixes an error in the recently added restrict-s3-bucket-policies.sentinel policy, replacing an occurrence of `break` with `continue`.
It also changes some comments in the MD file for tfconfig-functions.find_descendant_modules() to refer to module labels instead of names and fixes a broken link in that file.
And it makes a mior typographical change in aws-functions.sentinel to change `num_segments -1` to `num_segments-1`.

add restrict-resources-by-module-source.sentinel

---

governance/third-generation/cloud-agnostic/sentinel.hcl

I had forgotten to add the new policy to the cloud-agnosticsentinel.hcl file

add restrict-resources-by-module-source to sentinel.hcl

---

governance/third-generation/README.md
governance/third-generation/cloud-agnostic/restrict-resources-by-module-source.sentinel
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/fail-direct-nested-module.hcl
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/fail-nested-modules-2.hcl
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/fail-nested-modules.hcl
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/fail-non-nested-modules.hcl
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/mock-tfconfig-fail-direct-nested-module.sentinel
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/mock-tfconfig-fail-nested-modules-2.sentinel
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/mock-tfconfig-fail-nested-modules.sentinel
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/mock-tfconfig-fail-non-nested-modules.sentinel
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/mock-tfconfig-pass-direct-nested-module.sentinel
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/mock-tfconfig-pass-nested-modules.sentinel
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/mock-tfconfig-pass-non-nested-modules.sentinel
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/pass-direct-nested-module.hcl
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/pass-nested-modules.hcl
governance/third-generation/cloud-agnostic/test/restrict-resources-by-module-source/pass-non-nested-modules.hcl
governance/third-generation/common-functions/tfconfig-functions/docs/get_ancestor_module_source.md
governance/third-generation/common-functions/tfconfig-functions/docs/get_parent_module_address.md
governance/third-generation/common-functions/tfconfig-functions/tfconfig-functions.sentinel

This PR has significant updates to the restrict-resources-by-module-source.sentinel policy and adds 2 new functions to the tfconfig-functions.sentinel module: get_ancestor_module_source() and get_parent_module_address(). The policy now calls the first of these instead of get_module_source(). This allows the policy to determine the source of the first non-local ancestor module (one that does not have source starting with "./" or "../") from the resource's actual module in case its source is local.
The policy now handles the following things that it previously did not:
1. Local modules within allowed modules.
2. Direct references to nested modules of allowed modules. (e.g., `app.terraform.io/Cloud-Operations/s3-bucket/aws//modules/notification`)
3. Modules in the public registry (which will …

update restrict-resources-by-module-source policy

---

governance/third-generation/aws/restrict-egress-sg-rule-cidr-blocks.sentinel
governance/third-generation/aws/restrict-ingress-sg-rule-cidr-blocks.sentinel
governance/third-generation/aws/restrict-ingress-sg-rule-rdp.sentinel
governance/third-generation/aws/restrict-ingress-sg-rule-ssh.sentinel
governance/third-generation/azure/restrict-inbound-source-address-prefixes.sentinel
governance/third-generation/azure/restrict-outbound-destination-address-prefixes.sentinel

This fixes order of conditions in filters used in 4 AWS and 2 Azure policies that restrict CIDRs.  Those policies included `rc.change.after.type is "ingress"` or `rc.change.after.type is "ingress", but it was possible for these to return undefined if a resource was being permanently destroyed since `rc.change.after` would then be empty. I moved those checks to after this:
```
(rc.change.actions contains "create" or rc.change.actions contains "update" or
rc.change.actions contains "read" or rc.change.actions contains "no-op")
```
That then guarantees that the resource is not being deleted before rc.change.after.type is read.  (Recall that Sentinel has short-circuit logic, so if previous conditions are false, then later boolean expressions will not be read.)
Roger

fix order of filter conditions

---

operations/automation-script/README.md
operations/automation-script/loadAndRunWorkspace.sh

print outputs from run in the loadAndRunWorkspace.sh operations script. This uses the `?include=outputs` argument on the API call against the state version ID which then gives full information about the outputs.  As indicated in the comment starting at line 489, we could have instead retrieved state version output IDs from the relationships of the state version API call and could have then called the State Version Output API to retrieve details for each output. See https://www.terraform.io/docs/cloud/api/state-version-outputs.html#show-a-state-version-output

print outputs

---

governance/third-generation/cloud-agnostic/require-all-resources-from-pmr.sentinel
governance/third-generation/cloud-agnostic/test/require-all-resources-from-pmr/mock-tfconfig-pass-destroy.sentinel
governance/third-generation/cloud-agnostic/test/require-all-resources-from-pmr/mock-tfrun-fail.sentinel
governance/third-generation/cloud-agnostic/test/require-all-resources-from-pmr/mock-tfrun-pass-destroy.sentinel
governance/third-generation/cloud-agnostic/test/require-all-resources-from-pmr/mock-tfrun-pass.sentinel
governance/third-generation/cloud-agnostic/test/require-all-resources-from-pmr/pass-destroy.hcl
governance/third-generation/cloud-agnostic/test/require-all-resources-from-pmr/pass.hcl

I realized that this policy would fail if a destroy was being done. But in that case, we don't want to fail.
It now checks tfrun.is_destroy in addition to what it was already checking.

don't fail require-all-resources-from-pmr.sentinel if destroy

---

governance/third-generation/aws/restrict-sagemaker-notebooks.sentinel
governance/third-generation/common-functions/tfplan-functions/docs/find_datasources_by_provider.md
governance/third-generation/common-functions/tfplan-functions/docs/find_resources_by_provider.md
governance/third-generation/common-functions/tfplan-functions/tfplan-functions.sentinel
governance/third-generation/common-functions/tfstate-functions/docs/find_datasources_by_provider.md
governance/third-generation/common-functions/tfstate-functions/docs/find_resources_by_provider.md
governance/third-generation/common-functions/tfstate-functions/tfstate-functions.sentinel

This updates the find_resources_by_provider() and find_datasources_by_provider() functions for both the tfplan-functions and the tfstate-functions modules to make them more flexible in dealing with the different way that Terraform 0.13 and higher versions treat provider_name of resources in the tfplan/v2 and tfstate/v2 imports compared to the way that Terraform 0.12 did.  The difference was that 0.13 and higher give the full name of a provider such as "registry.terraform.io/hashicorp/aws" while 0.12 just gave "aws".
Previously, I had adjusted for that by telling users to use the long form name if using 0.13 or higher and to use the short form name if using 0.12.
Now, users can use either form with 0.13 and higher depending on their preference.  They must still use the short form with …

update find_by_provider functions

---

governance/third-generation/common-functions/tfplan-functions/tfplan-functions.sentinel

Currently, when an object has no elements, `to_string` outputs `{` instead of the expected `{}`. This change fixes that, thereby aligning the behavior more with how lists are handled (`[]`).

Fix the Ending Curly Brace in to_string

---

governance/third-generation/cloud-agnostic/restrict-terraform-versions.sentinel
governance/third-generation/cloud-agnostic/test/restrict-terraform-versions/fail.json
governance/third-generation/cloud-agnostic/test/restrict-terraform-versions/mock-tfplan-fail.sentinel
governance/third-generation/cloud-agnostic/test/restrict-terraform-versions/mock-tfplan-pass.sentinel
governance/third-generation/cloud-agnostic/test/restrict-terraform-versions/pass.json

Contributing a new policy to the example policy set.
The policy tests the terraform version used and flags it, if it is not from the allowed versions.

Added terraform version policy

---

governance/third-generation/azure/require-free-sec-center-subscription-pricing-for-vms.sentinel
governance/third-generation/azure/test/require-free-sec-center-subscription-pricing-for-vms/fail.hcl
governance/third-generation/azure/test/require-free-sec-center-subscription-pricing-for-vms/mock-tfplan-fail.sentinel
governance/third-generation/azure/test/require-free-sec-center-subscription-pricing-for-vms/mock-tfplan-pass.sentinel
governance/third-generation/azure/test/require-free-sec-center-subscription-pricing-for-vms/pass.hcl

Add policy that requires use of Free pricing tier on all Virtual Machines in Azure.

add require-free-sec-center-subscription-pricing-for-vms.sentinel

---

operations/automation-script/README.md
operations/automation-script/loadAndRunWorkspace-jq.sh
operations/automation-script/loadAndRunWorkspace-python.sh

I've added a jq version of loadAndRunWorkspace.sh called loadAndRunWorkspace-jq.sh which uses jq instead of python to parse the JSON documents returned by the Terraform Cloud API endpoints. I renamed the original script to loadAndRunWorkspace-python.sh.  I also updated the README.md for the scripts accordingly.  I did this because jq seems more modern than python.  I originally intended to replace python with jq, but then decided to keep the original script and rename it. This way, users have a choice.
I also updated the code that counted Sentinel policies to instead count Sentinel policy sets. This also affects some of the output which now reports how many Sentinel policy sets were found instead of how many policies were found.

add jq version of loadAndRunWorkspace.sh

---

governance/third-generation/cloud-agnostic/http-examples/README.md
governance/third-generation/cloud-agnostic/http-examples/use-latest-module-versions.hcl
governance/third-generation/cloud-agnostic/http-examples/use-latest-module-versions.sentinel

We now use pagination to retrieve the latest version from all private modules in the specified private registry (PMR).  We still limit the number of modules from the public registry since we don't think users should really be retrieving all modules from it. But we have increased the limit from 20 to 100.
Note that when retrieving versions of modules from a PMR, the API that is used only retrieves private modules.  It does not yet retrieve publically curated modules that actually live in the public registry but have been cross-referenced in the PMR.  See https://learn.hashicorp.com/tutorials/terraform/module-private-registry-add?in=terraform/modules

use pagination in use-latest-module-versions policy

---

governance/third-generation/cloud-agnostic/http-examples/use-latest-module-versions.sentinel

I had to change "namespace" to "organization" in the URL built in the get_public_registry_modules() function.
I also improved one message to say "the most recent version" instead of "the most version"

namespace to organization

---

governance/third-generation/cloud-agnostic/require-all-resources-from-pmr.sentinel
governance/third-generation/cloud-agnostic/test/require-all-resources-from-pmr/fail.hcl
governance/third-generation/cloud-agnostic/test/require-all-resources-from-pmr/mock-tfconfig-fail.sentinel
governance/third-generation/cloud-agnostic/test/require-all-resources-from-pmr/mock-tfconfig-pass-destroy.sentinel
governance/third-generation/cloud-agnostic/test/require-all-resources-from-pmr/mock-tfconfig-pass.sentinel
governance/third-generation/cloud-agnostic/test/require-all-resources-from-pmr/pass-destroy.hcl
governance/third-generation/cloud-agnostic/test/require-all-resources-from-pmr/pass.hcl

I've updated require-all-resources-from-pmr.sentinel to support multiple organizations instead of a single organization. This is desired since TFE customers can share modules between organizations.

multiple orgs in require-all-resources-from-pmr.sentinel

---

governance/README.md
governance/third-generation/README.md

Had space after `**` in boldface in both README.md files I edited in previous PR

Deprecate governance

---

governance/third-generation/gcp/enforce-mandatory-labels.sentinel
governance/third-generation/gcp/gcp-functions/docs/find_resources_with_standard_tags.md
governance/third-generation/gcp/gcp-functions/gcp-functions.sentinel
governance/third-generation/gcp/sentinel.hcl

Add GCP function to facilitate enforcing labels on multiple resources.  This is similar to the way its handled in the Azure function.

Bring GCP label enforcement up to parity with Azure tag enforcement
