hashicorp/terraform-guides

governance/README.md
governance/vmware/require-storage-drs.sentinel
governance/vmware/require_nfs41_and_kerberos.sentinel
governance/vmware/restrict-virtual-disk-size-and-type.sentinel
governance/vmware/restrict-vm-cpu-and-memory.sentinel
governance/vmware/restrict-vm-disk-size.sentinel

I added 5 VMware Sentinel policies that I created by examining the vSphere Provider documentation. I was not actually able to test these, but do expect them to work based on my previous experience writing Terraform Sentinel policies.

added vmware sentinel policies

---

infrastructure-as-code/k8s-cluster-gke/README.md
self-serve-infrastructure/k8s-services/main.tf
self-serve-infrastructure/k8s-services/variables.tf

Cats-n-dogs documentation update

---

infrastructure-as-code/gcp-compute-instance/main.tf

Had to change image to debian-9 since the debian-8 image is no longer available in GCP

changed to debian-9

---

README.md

fix typo reported in https://github.com/hashicorp/terraform-guides/issues/66

fix typo in readme under infrastructure-as-code

---

governance/gcp/pod_limit.sentinel

Adding pod limit check

---

infrastructure-as-code/k8s-cluster-openshift-aws/README.md
infrastructure-as-code/k8s-cluster-openshift-aws/main.tf
infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/02-vpc.tf
infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/03-security-groups.tf
infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/04-roles.tf
infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/05-nodes.tf
infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/06-dns.tf
infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/07-bastion.tf
infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/files/install-from-bastion.sh
infrastructure-as-code/k8s-cluster-openshift-aws/variables.tf

Add to add tag to names of some more AWS resources for OpenShift cluster deployment to support concurrent deployments in same AWS account

made changes to support concurrent deployments

---

operations/automation-script/README.md
operations/automation-script/configversion.json
operations/automation-script/loadAndRunWorkspace.sh

Added auto-queue-runs and set to false in configversion.json so that loading configuration no longer triggers initial run (that always failed since the name variable had not yet been set).
Also switched from python3 to python which works just as well.
And switched from atlas.hashicorp.com to app.terraform.io as default SaaS URL.

Automation script mods

---

infrastructure-as-code/terraform-0.12-examples/README.md
infrastructure-as-code/terraform-0.12-examples/first-class-expressions/main.tf
infrastructure-as-code/terraform-0.12-examples/for-expressions/lists-and-maps-with-for.tf
infrastructure-as-code/terraform-0.12-examples/for-expressions/main.tf
infrastructure-as-code/terraform-0.12-examples/generalized-splat-operator/main.tf
infrastructure-as-code/terraform-0.12-examples/new-template-syntax/actual_vote.txt
infrastructure-as-code/terraform-0.12-examples/new-template-syntax/main.tf
infrastructure-as-code/terraform-0.12-examples/new-template-syntax/rigged_vote.txt
infrastructure-as-code/terraform-0.12-examples/reliable-json-syntax/variable-correct.tf.txt
infrastructure-as-code/terraform-0.12-examples/reliable-json-syntax/variable-with-comment.tf.txt
infrastructure-as-code/terraform-0.12-examples/reliable-json-syntax/variable1.tf.json
infrastructure-as-code/terraform-0.12-examples/reliable-json-syntax/variable2.tf.txt
infrastructure-as-code/terraform-0.12-examples/reliable-json-syntax/variable3.tf.txt
infrastructure-as-code/terraform-0.12-examples/reliable-json-syntax/variable4.tf.txt
infrastructure-as-code/terraform-0.12-examples/rich-value-types/main.tf
infrastructure-as-code/terraform-0.12-examples/rich-value-types/network/main.tf
infrastructure-as-code/terraform-0.12-examples/rich-value-types/network/outputs.tf
infrastructure-as-code/terraform-0.12-examples/rich-value-types/network/variables.tf

Added my Terraform 0.12 examples that we used during Q4 SE training.  These had been in my own personal repository.

added terraform-0.12-examples

---

governance/vmware/restrict-vm-creation-hours

Added VMware policy to restrict hours when VMs can be created.

Add restrict hours policy

---

operations/README.md
operations/automation-script/README.md

I added a mention of the downloading of the apply log and state files in the operations directory README.md

mentioned apply log state files

---

operations/README.md
operations/automation-script/README.md
operations/automation-script/loadAndRunWorkspace.sh

Added the output of the TF plan to the workflow and silenced all the curl comands.

Added TF Plan

---

infrastructure-as-code/aws-lambda-ec2-lifecycles/terraform.tfvars

Removed terraform.tfvars file, recreated slack web hook

This should not have been committed to git

---

operations/automation-script/README.md
operations/automation-script/config/main.tf
operations/automation-script/workspace.template.json

Updated tf code in /code to be TF 0.12 compatible, modified workspace.template.json to include terraform-version specification, and updated readme to reflect changes.

Jray update automation script

---

operations/automation-script/README.md
operations/automation-script/deleteWorkspace.sh
operations/automation-script/loadAndRunWorkspace.sh
operations/sentinel-policies-scripts/README.md
operations/sentinel-policies-scripts/delete_policies.sh
operations/sentinel-policies-scripts/export_policies.sh
operations/sentinel-policies-scripts/import_policies.sh

Change ATLAS_TOKEN to TFE_TOKEN in scripts and README.md files.

ATLAS_TOKEN to TFE_TOKEN

---

governance/second-generation/cloud-agnostic/require-all-resources-from-pmr.sentinel
governance/second-generation/cloud-agnostic/test/require-all-resources-from-pmr/fail-0.11.json
governance/second-generation/cloud-agnostic/test/require-all-resources-from-pmr/fail-0.12.json
governance/second-generation/cloud-agnostic/test/require-all-resources-from-pmr/mock-tfconfig-fail-0.11.sentinel
governance/second-generation/cloud-agnostic/test/require-all-resources-from-pmr/mock-tfconfig-fail-0.12.sentinel
governance/second-generation/cloud-agnostic/test/require-all-resources-from-pmr/mock-tfconfig-pass-0.11.sentinel
governance/second-generation/cloud-agnostic/test/require-all-resources-from-pmr/mock-tfconfig-pass-0.12.sentinel
governance/second-generation/cloud-agnostic/test/require-all-resources-from-pmr/pass-0.11.json
governance/second-generation/cloud-agnostic/test/require-all-resources-from-pmr/pass-0.12.json

add new Sentinel policy to prevent resources in the root module and to require non-root modules loaded from the root module to come from the PMR.

add require-all-resources-from-pmr

---

governance/second-generation/cloud-agnostic/sentinel.hcl

I forgot to update the cloud-agnostic sentinel.hcl file to list the new prevent-non-root-providers.sentinel policy.

updated cloud-agnostic sentinel.hcl

---

governance/second-generation/README.md

minor correction in second-generation README.md about new policy set configuration files,  changing "policies checks" to "policy checks".

policies to policy

---

governance/second-generation/aws/test/require-private-acl-and-kms-for-s3-buckets/mock-tfplan-fail-acl-and-kms-0.12.sentinel
governance/second-generation/aws/test/require-private-acl-and-kms-for-s3-buckets/mock-tfplan-pass-0.12.sentinel
governance/second-generation/vmware/test/restrict-vm-cpu-and-memory/mock-tfplan-fail-cpu-and-memory-0.12.sentinel
governance/second-generation/vmware/test/restrict-vm-cpu-and-memory/mock-tfplan-pass-0.12.sentinel
governance/second-generation/vmware/test/restrict-vm-disk-size/mock-tfplan-fail-0.12.sentinel
governance/second-generation/vmware/test/restrict-vm-disk-size/mock-tfplan-pass-0.12.sentinel

I determined that some mocks that pretended to be for 0.12 were really generated from 0.11.  I re-generated them with 0.12.

convert some mocks to 0.12

---

infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/files/setup-master.sh
infrastructure-as-code/k8s-cluster-openshift-aws/modules/openshift/files/setup-node.sh
infrastructure-as-code/k8s-cluster-openshift-aws/variables.tf

Kernel updates were creating issues when installing packages needed by Ansible. This commit just performs a yum update using: `yum -exclude=kernel* update -y`

Exclude kernel updates in setup-master.sh and setup-node.sh

---

governance/second-generation/cloud-agnostic/blacklist-datasources.sentinel
governance/second-generation/cloud-agnostic/blacklist-providers.sentinel
governance/second-generation/cloud-agnostic/test/blacklist-datasources/fail-0.11.json
governance/second-generation/cloud-agnostic/test/blacklist-datasources/fail-0.12.json
governance/second-generation/cloud-agnostic/test/blacklist-datasources/mock-tfconfig-fail-0.11.sentinel
governance/second-generation/cloud-agnostic/test/blacklist-datasources/mock-tfconfig-fail-0.12.sentinel
governance/second-generation/cloud-agnostic/test/blacklist-datasources/mock-tfconfig-pass-0.11.sentinel
governance/second-generation/cloud-agnostic/test/blacklist-datasources/mock-tfconfig-pass-0.12.sentinel
governance/second-generation/cloud-agnostic/test/blacklist-datasources/pass-0.11.json
governance/second-generation/cloud-agnostic/test/blacklist-datasources/pass-0.12.json
governance/second-generation/cloud-agnostic/test/blacklist-providers/fail-0.11.json
governance/second-generation/cloud-agnostic/test/blacklist-providers/fail-0.12.json
governance/second-generation/cloud-agnostic/test/blacklist-providers/mock-tfconfig-fail-0.11.sentinel
governance/second-generation/cloud-agnostic/test/blacklist-providers/mock-tfconfig-fail-0.12.sentinel
governance/second-generation/cloud-agnostic/test/blacklist-providers/mock-tfconfig-pass-0.11.sentinel
governance/second-generation/cloud-agnostic/test/blacklist-providers/mock-tfconfig-pass-0.12.sentinel
governance/second-generation/cloud-agnostic/test/blacklist-providers/pass-0.11.json
governance/second-generation/cloud-agnostic/test/blacklist-providers/pass-0.12.json
governance/second-generation/common-functions/config/find_datasources_from_config.md
governance/second-generation/common-functions/config/find_datasources_from_config.sentinel
governance/second-generation/common-functions/plan/find_datasources_from_plan.md
governance/second-generation/common-functions/plan/find_datasources_from_plan.sentinel
governance/second-generation/common-functions/state/find_datasources_from_state.md
governance/second-generation/common-functions/state/find_datasources_from_state.sentinel

Added new Sentinel policies that can be used to blacklist specified providers and datasources.

blacklist providers and datasources

---

infrastructure-as-code/gcp-compute-instance/main.tf

Updated outputs for latest HCL 2, as indicated by broken TFC runs using v 0.12

Updated for TF 0.12

---

operations/automation-script/loadAndRunWorkspace.sh

This PR allows variables sent to workspaces with the TFC variables API using the loadAndRunWorkspace.sh script to have special characters including "&, "\", and "/".
First, it handles "&" and "\" specially before using sec by calling an escape_string() function that itself uses sed to add "\" before them.
```
escape_string()
{
printf '%s' "$1" | sed -e 's/\([&\]\)/\\\1/g'
}
```
This function is used in these lines:
```
fixedkey=$(escape_string "$key")
fixedvalue=$(escape_string "$value")
```
We do not fix other variables used in generating the variable.json payload file (organization, workspace, category, hcl, and sensitive) because the first two need to be legal org and workspace names anyways and the last three have fixed sets of values that would not have special characters.
Second, it …

special chars in vars

---

governance/second-generation/cloud-agnostic/limit-cost-by-workspace-type.sentinel
governance/second-generation/cloud-agnostic/restrict-cost-and-percentage-increase.sentinel

Add $ to two more cost estimate policies beyond the one that @jboero already fixed.

add $ to currency policies

---

operations/variable-scripts/README.md
operations/variable-scripts/other-variables.csv
operations/variable-scripts/set-variables.sh

adding support for variable description fields for TFC/E variable script

modified variable.sh, README, and example CSV

---

infrastructure-as-code/terraform-0.13-examples/module-depends-on/README.md

I made some improvements to the README.md of my new Terraform 0.13 module depends_on example.

improve module-depends-on README.md

---

governance/third-generation/cloud-agnostic/sentinel.hcl

Fix typo in sentinel.hcl for cloud-agnostic

---

governance/third-generation/cloud-agnostic/require-all-resources-from-pmr.sentinel

fix incorrect comment at top of policy.

fix comment

---

governance/third-generation/common-functions/tfconfig-functions/docs/find_descendant_modules.md

minor update to doc for tfconfig find_descendant_modules

---

governance/third-generation/aws/restrict-subnet-of-ec2-instances.sentinel
governance/third-generation/aws/test/restrict-subnet-of-ec2-instances/fail.json
governance/third-generation/aws/test/restrict-subnet-of-ec2-instances/mock-tfconfig-fail.sentinel
governance/third-generation/aws/test/restrict-subnet-of-ec2-instances/mock-tfconfig-pass.sentinel
governance/third-generation/aws/test/restrict-subnet-of-ec2-instances/pass.json

add policy that restricts subnet of EC2 instances

add restrict-subnet-of-ec2-instances.sentinel

---

governance/third-generation/README.md

Forgot to commit the change before pushing for last PR

update 3gen README.md

---

operations/sentinel-policies-scripts/create-policy-set-version.sh
operations/sentinel-policies-scripts/policy-set/restrict-sagemaker-notebooks.sentinel
operations/sentinel-policies-scripts/policy-set/sentinel.hcl

This script creates policy set version for an existing policy set and uploads the contents of the policy-set directory.

add create-policy-set-version.sh script

---

governance/third-generation/README.md

Update the governance/third-generation/README.md file, particularly the section about the tfconfig-functions Sentinel import which has a new function.  I also described recent changes which allows all the tfconfig filter functions to use top-level attributes AND those under the config map.
I also removed many occurences of "new" since the third-generation policies are no longer new.

updated 3g README.md tfconfig-functions

---

operations/automation-script/loadAndRunWorkspace.sh

Print workspace name in automation script to assist with debugging.

print workspace name

---

governance/third-generation/cloud-agnostic/sentinel.hcl

add new policy to sentinel.hcl file in cloud-agnostic directory.

add restrict-remote-state to sentinel.hcl

---

governance/third-generation/cloud-agnostic/restrict-remote-state.sentinel

There are some limitations of this policy from a security point of view.  I added comments to the top of the policy to explain them.

explain limitation of the policy
